/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CekReservasiRouteImport } from './routes/cek-reservasi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ReservasiRouteImport } from './routes/reservasi'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSkriningRouteImport } from './routes/_authenticated/skrining'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CekReservasiRoute = CekReservasiRouteImport.update({
  id: '/cek-reservasi',
  path: '/cek-reservasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasiRoute = ReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkriningRoute = AuthenticatedSkriningRouteImport.update({
  id: '/skrining',
  path: '/skrining',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artikel': typeof ArtikelRoute
  '/auth': typeof AuthRoute
  '/cek-reservasi': typeof CekReservasiRoute
  '/contact': typeof ContactRoute
  '/reservasi': typeof ReservasiRoute
  '/tiktok': typeof TiktokRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/skrining': typeof AuthenticatedSkriningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artikel': typeof ArtikelRoute
  '/auth': typeof AuthRoute
  '/cek-reservasi': typeof CekReservasiRoute
  '/contact': typeof ContactRoute
  '/reservasi': typeof ReservasiRoute
  '/tiktok': typeof TiktokRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/skrining': typeof AuthenticatedSkriningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/artikel': typeof ArtikelRoute
  '/auth': typeof AuthRoute
  '/cek-reservasi': typeof CekReservasiRoute
  '/contact': typeof ContactRoute
  '/reservasi': typeof ReservasiRoute
  '/tiktok': typeof TiktokRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/skrining': typeof AuthenticatedSkriningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artikel'
    | '/auth'
    | '/cek-reservasi'
    | '/contact'
    | '/reservasi'
    | '/tiktok'
    | '/dashboard'
    | '/profile'
    | '/skrining'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artikel'
    | '/auth'
    | '/cek-reservasi'
    | '/contact'
    | '/reservasi'
    | '/tiktok'
    | '/dashboard'
    | '/profile'
    | '/skrining'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/artikel'
    | '/auth'
    | '/cek-reservasi'
    | '/contact'
    | '/reservasi'
    | '/tiktok'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/skrining'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArtikelRoute: typeof ArtikelRoute
  AuthRoute: typeof AuthRoute
  CekReservasiRoute: typeof CekReservasiRoute
  ContactRoute: typeof ContactRoute
  ReservasiRoute: typeof ReservasiRoute
  TiktokRoute: typeof TiktokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-reservasi': {
      id: '/cek-reservasi'
      path: '/cek-reservasi'
      fullPath: '/cek-reservasi'
      preLoaderRoute: typeof CekReservasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservasi': {
      id: '/reservasi'
      path: '/reservasi'
      fullPath: '/reservasi'
      preLoaderRoute: typeof ReservasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skrining': {
      id: '/_authenticated/skrining'
      path: '/skrining'
      fullPath: '/skrining'
      preLoaderRoute: typeof AuthenticatedSkriningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSkriningRoute: typeof AuthenticatedSkriningRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSkriningRoute: AuthenticatedSkriningRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArtikelRoute: ArtikelRoute,
  AuthRoute: AuthRoute,
  CekReservasiRoute: CekReservasiRoute,
  ContactRoute: ContactRoute,
  ReservasiRoute: ReservasiRoute,
  TiktokRoute: TiktokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
